### ISSUE TITLE
Need ability to BIND separate from START

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs-sle#11]
When performing handover between ground stations, such as when using the Deep Space Network and transferring telemetry downlink from a station in Australia to a station in Spain, mission operators want the ability to BIND to a new ground station without performing START, so that if there are any problems connecting to the new ground station they can be identified before needing to get telemetry from the new ground station. Currently, enabling a SLE data link performs both a BIND and a START.

**Comment by xpromache** [comment]
Implemented in version 1.5.0
