### ISSUE TITLE
SLE links continue to retry after "connection refused", even if disabled

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs-sle#6]
To reproduce:

1. Enable an SLE data link to an IP address that will refuse the connection attempt.

Expected result: Event list shows "Failed to connect to the SLE provider: Connection refused: /<ip-addr:port>

2. Disable the SLE data link. (You can also disable all sub-links - does not affect behavior.)

Expected result: SLE connection attempts stop.
Actual result: SLE connection is retried every 30 seconds, as shown in the Events list.

**Comment by merose** [comment]
Does not seem to affect FCLTU links, just RAF and RCF. Not sure whether that is related to the number of sublinks. Our RAF and RCF data links have several virtual channels configured.

**Comment by merose** [comment]
It may be that `AbstractTmFrameLink.connect()` needs to check the enabled/disabled status before attempting the connection, since it can be called both from `TmSleLink.dostart()` (which does check that the link is enabled before calling) and also the retry code inside `connect()` (lines 129-135):

```
            if (!f.isSuccess()) {
                eventProducer.sendWarning("Failed to connect to the SLE provider: " + f.cause().getMessage());
                rsuh = null;
                if (reconnectionIntervalSec >= 0) {
                    workerGroup.schedule(() -> connect(), reconnectionIntervalSec, TimeUnit.SECONDS);
                }
            } else {
            ...
```

That call from the error handler calls `connect` again, and that will not have a check for the disabled state.

**Comment by merose** [comment]
The code in `TcSleLink` does include a check for disabled status, but it may be in the wrong place. The check is just before scheduling the reconnect (lines 125-127):

```
                if (!isDisabled() && reconnectionIntervalSec >= 0) {
                    workerGroup.schedule(() -> connect(), reconnectionIntervalSec, TimeUnit.SECONDS);
                }
```

However, this means that one additional connection attempt may occur _after_ disabling the link, which may be undesirable. I think it would be better to check at the top of `connect()` instead.

**Comment by xpromache** [comment]
pushed fix to master.
