### ISSUE TITLE
SLE data links should report their names in event messages

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs-sle#7]
For some ground providers, such as the Deep Space Network, multiple RCF connections need to be established (if using RCF). However, the event messages showing connection and disconnection do not display enough information to determine which data link is generating the event. As an example, this shows the connection of two RCF data links.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/1649381/116905685-28cfa980-abf4-11eb-8808-32582e2bcad1.png">

**Comment by xpromache** [comment]
I saw this has been fixed at some point, so closing the issue. Please reopen if it is not the case.
